version: '3'
services:

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8
      --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
      --innodb-flush-log-at-trx-commit=0 --bind-address=0.0.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=lemon
    volumes:
      - ./extras/initdb.d:/docker-entrypoint-initdb.d
      - /srv/lemonade/mysql-dev:/var/lib/mysql
    networks:
      default:
        aliases: [lemonade_db, db]
    restart: on-failure
    ports:
    - 33062:3306

  redis:
    image: redis:4
    networks:
      - default
    restart: on-failure

  thorn:
    build: ./thorn
    image: eubrabigsea/thorn
    environment:
      - RAILS_CORS_ORIGINS=*
    volumes:
      - ./config/database.yml:/usr/src/app/config/database.yml
    networks:
      - default
    restart: always

  limonero:
    build: ./limonero
    image: eubrabigsea/limonero
    volumes:
      - ./config/limonero-config.yaml:/usr/local/limonero/conf/limonero-config.yaml
      - /srv/lemonade/storage:/srv/storage
    networks:
      - default
    restart: always

  stand:
    build: ./stand
    image: eubrabigsea/stand
    volumes:
      - ./config/stand-config.yaml:/usr/local/stand/conf/stand-config.yaml
    networks:
      - default
    restart: always

  caipirinha:
    build: ./caipirinha
    image: eubrabigsea/caipirinha
    volumes:
      - ./config/caipirinha-config.yaml:/usr/local/caipirinha/conf/caipirinha-config.yaml
    networks:
      - default
    restart: always

  tahiti:
    build: ./tahiti
    image: eubrabigsea/tahiti
    volumes:
      - ./config/tahiti-config.yaml:/usr/local/tahiti/conf/tahiti-config.yaml
    networks:
      - default
    restart: always

  juicer:
    build: ./juicer
    image: eubrabigsea/juicer
    environment:
      - HADOOP_CONF_DIR=/usr/local/juicer/conf
    volumes:
      - ./config/juicer-config.yaml:/usr/local/juicer/conf/juicer-config.yaml
      - ./config/hdfs-site.xml:/usr/local/juicer/conf/hdfs-site.xml
      - /srv/lemonade/storage:/srv/storage
    networks:
      - default
    restart: always
    # Uncomment next lines if you are connecting to an external spark cluster
    #ports:
    #  - '37100-37399:37100-37399'

  citrus:
    build: ./citrus
    image: eubrabigsea/citrus
    ports:
      - '23456:8080'
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    restart: always

networks:
  default:
